### ISSUE TITLE
params[x] in this process with sizes [x, x] appears not to match sizes of the same param in process 0

### ISSUE THREAD

**Issue by forever208** [NVlabs/edm#11]
if people have this issue when training with multiple GPUs, try with python3.8 + PyTorch 1.12.1.
I had this error when using Python 3.9

**Comment by kugwzk** [comment]
How did you solve this problem? @forever208

**Comment by huanranchen** [comment]
> How did you solve this problem? @forever208

try with python3.8 + PyTorch 1.12.1.

**Comment by deJQK** [comment]
For anyone using multiple 4090 or 4090D GPUs to train the model, here is the proper config that works (or at least can run without reporting error):
```
name: edm
channels:
  - pytorch
  - nvidia
dependencies:
  - python>=3.8, < 3.10  # package build failures on 3.10
  - pip
  - click>=8.0
  - pillow>=8.3.1
  - scipy>=1.7.1
  - pytorch=1.13.0
  - psutil
  - requests
  - tqdm
  - imageio
  - pip:
    - imageio-ffmpeg>=0.4.3
    - pyspng
    - numpy==1.24.4  # numpy 1.24.4 works
```
Higher version of pytorch and python might cause the error as stated above, i.e. 

> params[x] ... not to match size ...

Higher version of numpy will cause error like 

> Could not infer dtype of numpy.uint8

and numpy 1.24.4 is required as mentioned [here](https://github.com/facebookresearch/segment-anything/issues/477#issuecomment-2185515518)

Pytorch 1.12.1 will cause error of gpu-architecture like

> nvrtc: error: invalid value for --gpu-architecture (-arch)

and higher version of pytorch is required (but not too high), as discussed [here](https://github.com/pytorch/pytorch/issues/87595#issuecomment-2063078827).

Hope the above helps!
