### ISSUE TITLE
VP checkpoints are trained using VE-scaling?

### ISSUE THREAD

**Issue by huanranchen** [NVlabs/edm#13]
I downloaded a vp checkpoint
```bash
CUDA_VISIBLE_DEVICES=6 python generate.py --outdir=out --seeds=0-63 --batch=64 --network=https://nvlabs-fi-cdn.nvidia.com/edm/pretrained/baseline/baseline-cifar10-32x32-uncond-vp.pkl --batch=4 --solver=euler
```

But I discovered that actually the code are sampling using ve scaling. When I force it to use vp scaling by 
```bash
CUDA_VISIBLE_DEVICES=6 python generate.py --outdir=out --seeds=0-63 --batch=64 --network=https://nvlabs-fi-cdn.nvidia.com/edm/pretrained/baseline/baseline-cifar10-32x32-uncond-vp.pkl --batch=4 --solver=euler --scaling=vp
```
It will output images like:
![concatenated](https://github.com/NVlabs/edm/assets/28839782/a8bd37b8-f3c7-46bd-b218-5dd648ebf15d)

Does this mean the VP models you trained are actually using ve scaling?

**Comment by JTT94** [comment]
What was the answer to this?

**Comment by Newbeeer** [comment]
Actually, their code uses VP scaling during sampling --- it's wrapped into the functioning call (`net(...)`)
