### ISSUE TITLE
ERROR when using multi-gpu training

### ISSUE THREAD

**Issue by Flu0XeT1n** [NVlabs/edm#18]
Hi, thanks for sharing your work. I can't train your model on my GPUS- two 4090. Is there any solution?
<img width="941" alt="image" src="https://github.com/NVlabs/edm/assets/56498265/7b9f01b7-3915-4af4-ac57-968132aa353c">

**Comment by LYMDLUT** [comment]
> Hi, thanks for sharing your work. I can't train your model on my GPUS- two 4090. Is there any solution? <img alt="image" width="941" src="https://user-images.githubusercontent.com/56498265/284062799-7b9f01b7-3915-4af4-ac57-968132aa353c.png">

I have met the same bug

**Comment by christopher-beckham** [comment]
I had a similar issue, make sure you're using PyTorch 1.12 as per the requirements.txt file.

**Comment by Flu0XeT1n** [comment]
> > Hi, thanks for sharing your work. I can't train your model on my GPUS- two 4090. Is there any solution? <img alt="image" width="941" src="https://user-images.githubusercontent.com/56498265/284062799-7b9f01b7-3915-4af4-ac57-968132aa353c.png">
> 
> I have met the same bug

I solved the problem by using PyTorch 1.13.1 with cuda 11.6 cudnn8.3.2.0

**Comment by marcoamonteiro** [comment]
@RachelTeamo to run on torch 2.1 replace line 89 in `training_loop.py`:
`ddp = torch.nn.parallel.DistributedDataParallel(net, device_ids=[device], broadcast_buffers=False)`
with
`ddp = torch.nn.parallel.DistributedDataParallel(net, device_ids=[dist.get_rank()], broadcast_buffers=False)`

I couldn't find any info in the PyTorch docs warning about the change in DDP API but this solved the issue for me.

**Comment by Shiien** [comment]
I solved this by ignoring line 79-84
```python
# if dist.get_rank() == 0:
#     with torch.no_grad():
#         images = torch.zeros([batch_gpu, net.img_channels, net.img_resolution, net.img_resolution], device=device)
#         sigma = torch.ones([batch_gpu], device=device)
#         labels = torch.zeros([batch_gpu, net.label_dim], device=device)
#         misc.print_module_summary(net, [images, sigma, labels], max_nesting=2)
```
And set `ddp = torch.nn.parallel.DistributedDataParallel(net, device_ids=[dist.get_rank()], broadcast_buffers=False)`
