### ISSUE TITLE
Possible error in the up-sampling function

### ISSUE THREAD

**Issue by Msadat97** [NVlabs/edm#2]
Hi all.

I have a question regarding the fused resampling in the Conv2d layer. When I use this option, the output shape does not correspond to a 2x up-sampling of the input. Here is a simple code to reproduce the issue:

```python
import torch
from training.networks import Conv2d

layer = Conv2d(64, 128, kernel=3, up=True, fused_resample=True, resample_filter=[1, 1])
x = torch.randn(2, 64, 32, 32)
print(layer(x).shape) # output shape is (2, 128, 60, 60)
```

Is this the desired behavior or a bug? (This is not compatible with the StyleGAN codebases.)

Thanks a lot in advance.

**Comment by tkarras** [comment]
Thank you for spotting this. Fixed.
